name: hrf
description: A new Flutter setup application for starting a project.

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0-nullsafety.0
  connectivity: ^3.0.3
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.0-prev2
  fancy_bottom_navigation: ^0.3.3
  firebase_core: ^1.7.0
  firebase_messaging: ^10.0.8
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^3.5.1
  flutter_html: ^2.0.0-nullsafety.0
  flutter_local_notifications: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  flutter_svg: ^0.22.0
  freezed: ^0.14.1
  get_it: ^7.2.0
  google_sign_in: ^5.1.0
  http: ^0.13.1
  image_picker: ^0.7.3
  package_info: ^2.0.0
  path_provider: ^2.0.1
  phone_number: ^0.12.0+1
  photo_view: ^0.13.0
  pin_code_fields: ^7.0.0
  place_picker: ^0.9.19
  provider: ^6.0.1
  share: ^2.0.1
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0-nullsafety.0
  url_launcher: ^6.0.18
  webview_flutter: ^2.0.2

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.otf
        - asset: assets/fonts/montserrat/Montserrat-Italic.otf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.otf
          weight: 700
